def subs(DNA, motif):

    motifIndices = ""
    currentIndex = 0
    lastIndex = 0

    while (DNA[lastIndex:].find(motif) != -1 ):

        if (currentIndex != 0 or lastIndex != 0):
            motifIndices += str(currentIndex + lastIndex) + " "

        lastIndex += currentIndex
        currentIndex = DNA[lastIndex:].find(motif) + 1

    #take out the last space and return
    return motifIndices[:-1]
    
Full_DNA_Strand = "TGTAGCAATGTAGCACTGTAGCAGGTGTAGCATCGACCCTTATCGTGTAGCATAAAGCTTGTAGCATGTAGCACGTTGTAGCACTGTAGCACAGCGTGTTGTAGCATGTAGCACATGTAGCAGGGTGTAGCAAGCGCTGTAGCATGTAGCATCGTGTAGCACATGTAGCATGTAGCACCTGTAGCATGTAGCATTGTAGCATGATGGTGTAGCAGCTGTAGCATGTAGCAGTCGTGTAGCAGTGTAGCAGGTGACCTGTAGCATCCCCTATGTAGCATACCCCTGTAGCATGTAGCATGTAGCACTGTAGCATTCTATGTAGCAACATGTAGCAACCACTTGTAGCAATGTAGCATTTGTAGCAACTGTAGCAGTCCTATGTAGCAAAGCGTTGTAGCATGTAGCAGTGTAGCACGGTACTCTTTGTAGCAAACGGGTGTAGCACCCCCTTGTAGCATGTAGCATGTAGCACTGTAGCATGTAGCAGCTGTAGCACCCTGTAGCATTTTATGTAGCATGTAGCAGTACCACAGTGTAGCACTGTGTGTAGCAGAAGGCATGTAGCACTTGTAGCATTTTGTAGCATATGTAGCATGTAGCATGTAGCACGTTCTGTAGCATGTAGCAGCGATGTAGCACTCTGGGTGTAGCAATTTAGGGGAATGTGTAGCATGTAGCATGTGTAGCAGGCCGTGTAGCAGGGTGTAGCAGTGTAGCATGTAGCATTAAATGTAGCAATGTAGCAGCTAAGTGTAGCACTGTAGCACACCGGTTGTAGCATGTAGCAGTGTAGCACTGTAGCATAGGCATGTTGTAGCAGATGTAGCATCTGTAGCATACCTGTGTAGCA"
Motif = "TGTAGCATG"

print(subs(Full_DNA_Strand, Motif))